const mongoose = require('mongoose');
const PropertyFeatures = mongoose.model(
  'PropertyFeatures',
  new mongoose.Schema({
    // main features
    ac: String,
    builtInYear: String,
    view: String,
    bed: String,
    airConditioner: String,
    heater: String,
    facing: {
      type: String,
      // enum: ['N', 'S', 'E', 'W', 'NW', 'NE', 'SE', 'SW'],
    },
    totalCapacity: String,
    highSpeedInternet: String,
    parkingSpaces: String,
    publicParking: String,
    undergroundParking: String,
    attachedBathroom: String,
    attachedBalcony: String,
    lobbyInBuilding: String,
    elevators: String,
    serviceElevatorsInBuilding: String,
    elevatorOrLift: String,
    doubleGlazedWindows: String,
    centralAirConditioning: String,
    centralHeating: String,
    flooring: {
      type: String,
      // enum: ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'],
    },
    electricityBackup: {
      type: String,
      // enum: ['None', 'Generator', 'UPS', 'Solar', 'Other'],
    },
    wasteDisposal: String,
    floors: String,
    cornerProperty: String,
    gatedCommunity: String,
    hiSpeedInternet: String,
    backupPowerOptions: String,
    otherMainFeatures: [{ type: String }],

    // main features (2)
    noOfUnits: String,
    possession: String,
    parkFacing: String,
    disputed: String,
    file: String,
    balloted: String,
    sewerage: String,
    boundaryWall: String,
    extraLand: String,
    mainBoulevard: String,
    irrigation: String,
    tubeWells: String,
    accessibleByRoad: String,
    parameterFencing: String,
    landFertility: String,
    boundaryLines: String,
    nearbyWaterResources: String,
    officeHoursTiming: String,
    otherPlotFeatures: [{ type: String }],

    // main features (3)
    wifi: String,
    washingMachine: String,
    fridge: String,
    cupboard: { type: String, 
      // enum: ['Private', 'Shared'] 
    },
    microwave: String,
    tableAndChair: { type: String, 
      // enum: ['Private', 'Shared'] 
    },
    dailyCleaningService: String,
    inhousePrinting: String,
    inhouseScanning: String,
    inhouseCopying: String,
    inhouseProjector: String,
    operationalHours: String,
    prayerArea: String,
    lockers: String,
    utilities: String,
    electricity: String,
    gas: String,
    water: String,
    maintenance: String,
    securityDeposit: String,

    // business and communication
    broadbandInternetAccess: String,
    satelliteOrCable: String,
    businessCenterOrMediaRoom: String,
    intercom: String,
    atmMachines: String,
    otherBusinessAndCommunicationFeatures: [{ type: String }],
    conferenceRoomInBuilding: String,

    // rooms
    bathrooms: String,
    servantsQuarters: String,
    drawingRoom: String,
    diningRoom: String,
    kitchen: String,
    studyRoom: String,
    prayerRoom: String,
    powderRoom: String,
    gym: String,
    storeRoom: String,
    steamRoom: String,
    loungeOrSittingRoom: String,
    laundryRoom: String,
    otherRooms: [{ type: String }],

    // community features
    communityLawnOrGarden: String,
    communitySwimmingPool: String,
    communityGym: String,
    firstAidOrMedicalCenter: String,
    dayCareCenter: String,
    kidsPlayArea: String,
    barbecueArea: String,
    mosque: String,
    communityCenter: String,
    otherCommunityFeatures: [{ type: String }],

    // nearby locations
    nearbySchools: String,
    nearbyHospitals: String,
    nearbyShoppingMalls: String,
    nearbyRestaurants: String,
    distanceFromAirport: String,
    nearbyPublicTransport: String,
    otherNearbyPlaces: [{ type: String }],

    // other facilities
    maintenanceStaff: String,
    securityStaff: String,
    laundryOrDryCleaning: String,
    communalOrSharedKitchen: String,
    facilitiesForDisabled: String,
    petPolicy: String,
    cctvSecurity: String,
    otherFacilities: [{ type: String }],
    cafeteria: String,
    supportStaff: String,
    frontDeskStaff: String,
    teaOrCoffee: String,
    drinkingWater: String,
    diningArea: String,
    indoorGames: String,
    lawn: String,
    indoorGym: String,
    washrooms: String,

    // healthcare and recreational
    lawnOrGarden: String,
    swimmingPool: String,
    sauna: String,
    jacuzzi: String,
    otherHealthcareAndRecreationalFeatures: [{ type: String }],
    cricketGround: String,
    footballGround: String,
    carromBoard: String,
    tableTennis: String,
    snooker: String,
    barbecueArea: String,
    bonfireArea: String,

    // Rules
    smokingPolicy: String,
    funLovingOccupants: String,
    chillLandlord: String,
    houseHelp: String,
    guestAllowed: String,
  })
);
module.exports = PropertyFeatures;
